package me.ele.talaris.hermes.client;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * 
 * @generated
 */

public enum THermesTemplateVerifyStatus implements org.apache.thrift.TEnum {
	PENDING(0), SUCCESS(1), FAIL(2);

	private final int value;

	private THermesTemplateVerifyStatus(int value) {
		this.value = value;
	}

	/**
	 * Get the integer value of this enum value, as defined in the Thrift IDL.
	 */
	public int getValue() {
		return value;
	}

	/**
	 * Find a the enum type by its integer value, as defined in the Thrift IDL.
	 * 
	 * @return null if the value is not found.
	 */
	public static THermesTemplateVerifyStatus findByValue(int value) {
		switch (value) {
		case 0:
			return PENDING;
		case 1:
			return SUCCESS;
		case 2:
			return FAIL;
		default:
			return null;
		}
	}
}
