package me.ele.talaris.hermes.client;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * 
 * @generated
 */

public enum THermesNotificationType implements org.apache.thrift.TEnum {
	TASK_STATUS_CHANGED(0), TEMPLATE_STATUS_CHANGED(1), USER_REPLY_RECEIVED(2);

	private final int value;

	private THermesNotificationType(int value) {
		this.value = value;
	}

	/**
	 * Get the integer value of this enum value, as defined in the Thrift IDL.
	 */
	public int getValue() {
		return value;
	}

	/**
	 * Find a the enum type by its integer value, as defined in the Thrift IDL.
	 * 
	 * @return null if the value is not found.
	 */
	public static THermesNotificationType findByValue(int value) {
		switch (value) {
		case 0:
			return TASK_STATUS_CHANGED;
		case 1:
			return TEMPLATE_STATUS_CHANGED;
		case 2:
			return USER_REPLY_RECEIVED;
		default:
			return null;
		}
	}
}
