package me.ele.talaris.hermes.client;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

/**
 * Enums
 */
public enum THermesTaskStatus implements org.apache.thrift.TEnum {
	INITIAL(0), SENDING(1), SUCCESS(2), FAIL(3), PARTIAL_SUCCESS(4), TIMEOUT(5);

	private final int value;

	private THermesTaskStatus(int value) {
		this.value = value;
	}

	/**
	 * Get the integer value of this enum value, as defined in the Thrift IDL.
	 */
	public int getValue() {
		return value;
	}

	/**
	 * Find a the enum type by its integer value, as defined in the Thrift IDL.
	 * 
	 * @return null if the value is not found.
	 */
	public static THermesTaskStatus findByValue(int value) {
		switch (value) {
		case 0:
			return INITIAL;
		case 1:
			return SENDING;
		case 2:
			return SUCCESS;
		case 3:
			return FAIL;
		case 4:
			return PARTIAL_SUCCESS;
		case 5:
			return TIMEOUT;
		default:
			return null;
		}
	}
}
